### ISSUE TITLE
Weekdays wrong on 2021 dataset

### ISSUE THREAD

**Issue by pvujic** [t1dtools/wrapped#2]
While doing some tests with my dataset, I encountered that 2021 results had wrong weekdays.

2021 started with a Friday and the application is showing a Tuesday.
![Screenshot 2023-01-05 at 19 29 42](https://user-images.githubusercontent.com/28774924/210854077-759dff1e-a54c-4c3a-b4a8-f320e735f806.png)

**Comment by AndreasStokholm** [comment]
Huh, that's strange. I just tried it with dummy data, and there the year starts on Friday as it should. Are you able to provide the data you used in an anonymized format?

Great control btw! 🤯
